### ISSUE TITLE
Support for Ropsten in safe_creator?

### ISSUE THREAD

**Issue by mverzilli** [gnosis/safe-cli#30]
Hi! Thanks for your work on the safe-cli, it's a super useful tool! I was wondering why it doesn't support Ropsten. Is that a permanent decision or are there any plans to support it? 

I managed to use the script to deploy a Safe to Ropsten by changing the addresses in these lines:

```python
# Support only Mainnet, Rinkeby, Goerli and Kovan
    safe_contract_address = '0x34CfAC646f301356fAa8B21e94227e3583Fe3F5F'
    proxy_factory_address = '0x76E2cFc1F5Fa8F6a5b3fC4c8F4788F0116861F9B'
    callback_handler_address = '0xd5D82B6aDDc9027B22dCA772Aa68D5d74cdBdF44'
```

To addresses corresponding to instances of those contracts that I deployed to Ropsten. It worked as is, so I was curious whether there's a deeper reason not to support Ropsten. 

Thank you!

**Comment by Uxio0** [comment]
Hi @mverzilli ,

Good to hear that, I'm glad you are finding it useful. We are not supporting Ropsten as our official contracts are not deployed on Ropsten and we don't plan to do that soon (our devs and users work with Rinkeby, Goerli and Kovan basically), that's why is not working with Ropsten out of the box.

I added command line flags to the `safe_creator` so the addresses can be specified on the command line and users don't have to edit the source code.

Kind regards
