### ISSUE TITLE
this is not a cli 

### ISSUE THREAD

**Issue by AndreiD** [gnosis/safe-cli#32]
So I was expecting a binary app, with some config file somewhere that you can run without having to troubleshoot python.

python ...at least on ubuntu 18.04 is by default 2 or 3.6. You say you need to upgrade it...I have to search how to upgrade it because I don't use python for my shit. 
Now besides python you also have some virtual env shit that I barely understand
and lastly, after installing everything  you have some kind of app, that behaves like CLI but you have to enter inside it from a script !?

**do you realise how hard it is for non-python developer to work with what you did here ?** If you don't, then I'm telling you that this is just not usable.

**Comment by AndreiD** [comment]
I just want a simple interface, that enables the usual operations to be done in the normal CLI mode... a binary release. Is it too much to ask ?

**Comment by Uxio0** [comment]
Hi @AndreiD and thanks your reaching us.

> So I was expecting a binary app, with some config file somewhere that you can run without having to troubleshoot python.

I understand the issue, but packaging a python app as a binary it's not really straight forward, so we decided not to do that for now as CLI is still on Beta.

> python ...at least on ubuntu 18.04 is by default 2 or 3.6. You say you need to upgrade it...

We count on systems to have Python 3.7, it's required for some basic dependencies we use and was released on June 2018, but I understand updating could be difficult or not possible for some people.

> do you realise how hard it is for non-python developer to work with what you did here ?

**Comment by Uxio0** [comment]
Hi @AndreiD and thanks your reaching us.

> So I was expecting a binary app, with some config file somewhere that you can run without having to troubleshoot python.

I understand the issue, but packaging a python app as a binary it's not really straight forward, so we decided not to do that for now as CLI is still on Beta.

> python ...at least on ubuntu 18.04 is by default 2 or 3.6. You say you need to upgrade it...

We count on systems to have Python 3.7, it's required for some basic dependencies we use and was released on June 2018, but I understand updating could be difficult or not possible for some people.

> Now besides python you also have some virtual env shit that I barely understand

You don't need to, `virtualenv` it's included since python 3.7 and should be ok if you follow the steps from README.
